# Generated by Django 6.0.4 on 2026-05-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='兴趣名称')),
                ('icon', models.CharField(default='bi-heart', max_length=50, verbose_name='Bootstrap图标类名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hobbies/', verbose_name='配图')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '兴趣爱好',
                'verbose_name_plural': '兴趣爱好',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('color', models.CharField(choices=[('primary', '蓝色'), ('secondary', '灰色'), ('success', '绿色'), ('danger', '红色'), ('warning', '黄色'), ('info', '青色'), ('dark', '黑色')], default='primary', max_length=20, verbose_name='标签颜色')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '个人标签',
                'verbose_name_plural': '个人标签',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='campusactivity',
            options={'ordering': ['order', '-start_date'], 'verbose_name': '校园实践', 'verbose_name_plural': '校园实践'},
        ),
        migrations.AlterModelOptions(
            name='internship',
            options={'ordering': ['order', '-start_date'], 'verbose_name': '实习/工作经历', 'verbose_name_plural': '实习/工作经历'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-start_date'], 'verbose_name': '项目经历', 'verbose_name_plural': '项目经历'},
        ),
        migrations.AddField(
            model_name='campusactivity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='活动配图'),
        ),
        migrations.AddField(
            model_name='campusactivity',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='internship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='internships/', verbose_name='配图'),
        ),
        migrations.AddField(
            model_name='internship',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='项目配图'),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
