# Generated by Django 6.0.4 on 2026-05-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_hobby_tag_alter_campusactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_intention',
            field=models.CharField(blank=True, max_length=200, verbose_name='求职意向'),
        ),
    ]
