# Generated by Django 6.0.4 on 2026-05-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_profile_job_intention'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order', '-start_date'], 'verbose_name': '教育经历', 'verbose_name_plural': '教育经历'},
        ),
        migrations.AddField(
            model_name='education',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='educations/', verbose_name='学校配图'),
        ),
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
