# Generated by Django 6.0.4 on 2026-05-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_education_options_education_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', '电话'), ('qq', 'QQ'), ('wechat', '微信'), ('telegram', 'Telegram'), ('twitter', 'Twitter'), ('location', '位置')], max_length=50, verbose_name='联系方式类型')),
                ('icon', models.CharField(default='bi-envelope', max_length=50, verbose_name='Bootstrap图标类名')),
                ('value', models.CharField(max_length=200, verbose_name='联系方式')),
                ('url', models.URLField(blank=True, verbose_name='链接（可选）')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '联系信息',
                'verbose_name_plural': '联系信息',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitionDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='展览名称')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exhibitions/', verbose_name='配图')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '逛展日记',
                'verbose_name_plural': '逛展日记',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='Hero标题（副标题）')),
                ('hero_description', models.TextField(blank=True, verbose_name='Hero描述')),
                ('section_title_projects', models.CharField(default='个人项目', max_length=100, verbose_name='项目区块标题')),
                ('section_title_skills', models.CharField(default='专业技能', max_length=100, verbose_name='技能区块标题')),
                ('section_title_music', models.CharField(default='音乐创作', max_length=100, verbose_name='音乐区块标题')),
                ('section_title_exhibitions', models.CharField(default='逛展日记', max_length=100, verbose_name='逛展区块标题')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '首页配置',
                'verbose_name_plural': '首页配置',
            },
        ),
        migrations.CreateModel(
            name='HomePageProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('icon', models.CharField(default='bi-folder', max_length=50, verbose_name='Bootstrap图标类名')),
                ('description', models.TextField(verbose_name='项目描述')),
                ('url', models.URLField(blank=True, verbose_name='项目链接')),
                ('technologies', models.CharField(blank=True, max_length=500, verbose_name='使用技术（用逗号分隔）')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '首页项目',
                'verbose_name_plural': '首页项目',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomePageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='技能分类')),
                ('icon', models.CharField(default='bi-tools', max_length=50, verbose_name='Bootstrap图标类名')),
                ('skills', models.TextField(verbose_name='技能列表（每行一个技能）')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '首页技能分类',
                'verbose_name_plural': '首页技能分类',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MusicCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作品名称')),
                ('original_author', models.CharField(blank=True, max_length=100, verbose_name='原作者')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='版本')),
                ('url', models.URLField(verbose_name='作品链接')),
                ('views', models.IntegerField(default=0, verbose_name='播放量')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '音乐创作',
                'verbose_name_plural': '音乐创作',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='平台名称')),
                ('icon', models.CharField(default='bi-github', max_length=50, verbose_name='Bootstrap图标类名')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '社交链接',
                'verbose_name_plural': '社交链接',
                'ordering': ['order'],
            },
        ),
    ]
