# Generated by Django 6.0.4 on 2026-05-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_contactinfo_exhibitiondiary_homeconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='icons/contact/', verbose_name='自定义图标图片'),
        ),
        migrations.AddField(
            model_name='homepageproject',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='icons/projects/', verbose_name='自定义图标图片'),
        ),
        migrations.AddField(
            model_name='homepageskill',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='icons/skills/', verbose_name='自定义图标图片'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='icons/social/', verbose_name='自定义图标图片'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='icon',
            field=models.CharField(blank=True, default='bi-envelope', max_length=50, verbose_name='Bootstrap图标类名'),
        ),
        migrations.AlterField(
            model_name='homepageproject',
            name='icon',
            field=models.CharField(blank=True, default='bi-folder', max_length=50, verbose_name='Bootstrap图标类名'),
        ),
        migrations.AlterField(
            model_name='homepageskill',
            name='icon',
            field=models.CharField(blank=True, default='bi-tools', max_length=50, verbose_name='Bootstrap图标类名'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(blank=True, default='bi-github', max_length=50, verbose_name='Bootstrap图标类名'),
        ),
    ]
