# Generated by Django 6.0.4 on 2026-05-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_contactinfo_icon_image_homepageproject_icon_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-envelope', max_length=100, verbose_name='图标类名（Bootstrap: bi-xxx / Font Awesome: fas/fa/fab fa-xxx）'),
        ),
        migrations.AlterField(
            model_name='homepageproject',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-folder', max_length=100, verbose_name='图标类名（Bootstrap: bi-xxx / Font Awesome: fas/fa/fab fa-xxx）'),
        ),
        migrations.AlterField(
            model_name='homepageskill',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-tools', max_length=100, verbose_name='图标类名（Bootstrap: bi-xxx / Font Awesome: fas/fa/fab fa-xxx）'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(blank=True, default='fab fa-github', max_length=100, verbose_name='图标类名（Bootstrap: bi-xxx / Font Awesome: fas/fa/fab fa-xxx）'),
        ),
    ]
