# Generated by Django 6.0.4 on 2026-05-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_contactinfo_icon_alter_homepageproject_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='个人标题（副标题）')),
                ('description', models.TextField(blank=True, verbose_name='个人简介')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/home/', verbose_name='头像')),
                ('resume_link', models.URLField(blank=True, default='/resume/', verbose_name='简历链接')),
                ('contact_link', models.CharField(blank=True, default='#contact', max_length=200, verbose_name='联系锚点')),
                ('resume_button_text', models.CharField(default='查看简历', max_length=50, verbose_name='简历按钮文字')),
                ('contact_button_text', models.CharField(default='联系我', max_length=50, verbose_name='联系按钮文字')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '首页个人介绍',
                'verbose_name_plural': '首页个人介绍',
            },
        ),
    ]
