# Generated by Django 6.0.4 on 2026-05-03 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_aboutpageinfo_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('website', models.URLField(blank=True, verbose_name='网站')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('avatar', models.CharField(blank=True, default='', max_length=200, verbose_name='头像URL（可选）')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('is_approved', models.BooleanField(default=True, verbose_name='是否通过审核')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='resume.comment', verbose_name='父评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created_at'],
            },
        ),
    ]
